[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "arma_class_parser"
author = "antistasi_tools"
classifiers = ["License :: OSI Approved :: MIT License"]
description-file = "README.md"
requires = [

]




[tool.flit.scripts]
